[package]
name = "zk_evm"
version = "0.1.0"
authors = ["therealyingtong <yingtong@z.cash>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ff = "0.10"
halo2 = "0.0"
pasta_curves = "0.1"
bigint = "4"

[patch.crates-io]
halo2 = { git = "https://github.com/zcash/halo2.git", rev = "d04b532368d05b505e622f8cac4c0693574fbd93" }
